#!/bin/bash
#
# setup-tunnel.sh — Start your NAMED Cloudflare Tunnel (stable domain), update .env
#
# Uses your paid tunnel + domain instead of the throwaway *.trycloudflare.com
# quick tunnel. Two auth modes (set in .env):
#
#   A) TOKEN auth (dashboard-managed ingress — recommended if you created the
#      tunnel in the Cloudflare Zero Trust dashboard):
#        CLOUDFLARE_TUNNEL_TOKEN=<long token>
#        CLOUDFLARE_TUNNEL_DOMAIN=chat.yourdomain.com
#      → runs: cloudflared tunnel run --token <token>
#      → the public hostname is configured in the dashboard (Networks → Tunnels
#        → <tunnel> → Public Hostnames → <domain> → http://localhost:3199)
#
#   B) CERT auth (local config — tunnel + ingress managed from this repo):
#        CLOUDFLARE_TUNNEL_ID=<uuid>          (cloudflared tunnel create <name>)
#        CLOUDFLARE_TUNNEL_DOMAIN=chat.yourdomain.com
#      → generates safe/cloudflared/config.yml (ingress: domain → localhost:PORT)
#      → runs: cloudflared tunnel run <ID> --config safe/cloudflared/config.yml
#
# Either way the public URL is deterministic: https://$CLOUDFLARE_TUNNEL_DOMAIN
#
# Also:
#   - Updates WEBHOOK_BASE_URL in .env to https://<domain>
#   - Updates the GCloud Pub/Sub push endpoint (if configured)
#
# Usage:
#   ./mcp/webhook-server/scripts/setup-tunnel.sh
#   npm run webhook:tunnel
#
# Prerequisites:
#   - cloudflared installed (brew install cloudflared)
#   - .env has CLOUDFLARE_TUNNEL_TOKEN (mode A) OR CLOUDFLARE_TUNNEL_ID (mode B)
#   - gcloud CLI authenticated (only for the Pub/Sub update step)
#

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
CF_DIR="$PROJECT_DIR/safe/cloudflared"
CONFIG_FILE="$CF_DIR/config.yml"
PID_FILE="$CF_DIR/tunnel.pid"

# ── Load .env (line-by-line to handle special chars safely) ──
if [ -f "$ENV_FILE" ]; then
  while IFS='=' read -r key val || [ -n "$key" ]; do
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    export "$key=$val"
  done < "$ENV_FILE"
fi

PORT="${WEBHOOK_PORT:-3199}"
SUBSCRIPTION="${GMAIL_PUBSUB_SUBSCRIPTION:-}"
TUNNEL_ID="${CLOUDFLARE_TUNNEL_ID:-}"
TUNNEL_TOKEN="${CLOUDFLARE_TUNNEL_TOKEN:-}"
TUNNEL_DOMAIN="${CLOUDFLARE_TUNNEL_DOMAIN:-}"
BASE_URL="https://${TUNNEL_DOMAIN}"

if ! command -v cloudflared &>/dev/null; then
  echo "❌ cloudflared not found. Install it:"
  echo "   brew install cloudflared"
  exit 1
fi

echo "=========================================="
echo "  Named Cloudflare Tunnel + Pub/Sub Setup"
echo "=========================================="
echo ""

# ── Validate config ──
if [ -z "$TUNNEL_DOMAIN" ]; then
  echo "❌ CLOUDFLARE_TUNNEL_DOMAIN is not set in .env (e.g. chat.yourdomain.com)"
  echo "   Add it and a CLOUDFLARE_TUNNEL_TOKEN (mode A) or CLOUDFLARE_TUNNEL_ID (mode B)."
  exit 1
fi

MODE=""
if [ -n "$TUNNEL_TOKEN" ]; then
  MODE="token"
elif [ -n "$TUNNEL_ID" ]; then
  MODE="cert"
else
  echo "❌ Neither CLOUDFLARE_TUNNEL_TOKEN (mode A) nor CLOUDFLARE_TUNNEL_ID (mode B) is set."
  echo "   See the header of this script for both options."
  exit 1
fi
echo "🚇 Mode: $MODE  →  $BASE_URL (port $PORT)"

# ── Stop any previous tunnel from this repo ──
if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE" 2>/dev/null)
  if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "   Stopping previous tunnel (PID $OLD_PID)..."
    kill "$OLD_PID" 2>/dev/null
    sleep 1
  fi
  rm -f "$PID_FILE"
fi

# ── 1. Generate config for cert mode ──
if [ "$MODE" = "cert" ]; then
  mkdir -p "$CF_DIR"
  CREDS_FILE="${HOME}/.cloudflared/${TUNNEL_ID}.json"
  if [ ! -f "$CREDS_FILE" ]; then
    echo "❌ Tunnel credentials not found at $CREDS_FILE"
    echo "   If you created the tunnel elsewhere, run 'cloudflared tunnel login' here,"
    echo "   or use mode A (CLOUDFLARE_TUNNEL_TOKEN) instead."
    exit 1
  fi
  cat > "$CONFIG_FILE" <<EOF
# Generated by setup-tunnel.sh — do not edit.
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}

ingress:
  - hostname: ${TUNNEL_DOMAIN}
    service: http://localhost:${PORT}
  - service: http_status:404
EOF
  echo "   ✅ Wrote $CONFIG_FILE (${TUNNEL_DOMAIN} → http://localhost:${PORT})"
fi

# ── 2. Start the tunnel ──
echo "🚇 Starting Cloudflare Tunnel..."
LOG_FILE="$CF_DIR/tunnel.log"
mkdir -p "$CF_DIR"

if [ "$MODE" = "token" ]; then
  cloudflared tunnel --no-autoupdate run --token "$TUNNEL_TOKEN" > "$LOG_FILE" 2>&1 &
else
  cloudflared tunnel --no-autoupdate --config "$CONFIG_FILE" run "$TUNNEL_ID" > "$LOG_FILE" 2>&1 &
fi
TUNNEL_PID=$!
echo "$TUNNEL_PID" > "$PID_FILE"
echo "   PID: $TUNNEL_PID  (logs: $LOG_FILE)"

# ── 3. Wait for the tunnel to come up ──
echo "   Waiting for $BASE_URL to respond..."
TUNNEL_UP=false
for i in $(seq 1 45); do
  if curl -sf -m 3 "$BASE_URL/health" &>/dev/null; then
    TUNNEL_UP=true
    break
  fi
  # If the process died, stop waiting
  if ! kill -0 "$TUNNEL_PID" 2>/dev/null; then
    echo "   ❌ cloudflared exited early. Last log lines:"
    tail -15 "$LOG_FILE" 2>/dev/null
    rm -f "$PID_FILE"
    exit 1
  fi
  sleep 2
done

if [ "$TUNNEL_UP" = false ]; then
  echo "   ⚠️  Tunnel process is running but $BASE_URL/health did not respond yet."
  echo "   This usually means the webhook server isn't running on port $PORT"
  echo "   or the public hostname isn't configured in the Cloudflare dashboard."
  echo "   Last log lines:"
  tail -15 "$LOG_FILE" 2>/dev/null
else
  echo "   ✅ Tunnel is live: $BASE_URL"
fi

# ── 4. Update .env with the stable URL ──
echo ""
echo "📝 Updating WEBHOOK_BASE_URL in .env → $BASE_URL"
if grep -q '^WEBHOOK_BASE_URL=' "$ENV_FILE"; then
  sed -i '' "s|^WEBHOOK_BASE_URL=.*|WEBHOOK_BASE_URL=$BASE_URL|" "$ENV_FILE"
else
  echo "WEBHOOK_BASE_URL=$BASE_URL" >> "$ENV_FILE"
fi
export WEBHOOK_BASE_URL="$BASE_URL"
echo "   ✅ Done"

# ── 5. Update GCloud Pub/Sub push endpoint ──
if [ -n "$SUBSCRIPTION" ]; then
  echo ""
  echo "📧 Updating GCloud Pub/Sub subscription push endpoint..."
  echo "   Subscription: $SUBSCRIPTION"
  echo "   Push endpoint: ${BASE_URL}/webhooks/gmail/push"
  cd "$SCRIPT_DIR"
  node update-pubsub-endpoint.js 2>&1 || echo "   ⚠️  Pub/Sub update failed — check GOOGLE_APPLICATION_CREDENTIALS"
  cd "$PROJECT_DIR"
else
  echo ""
  echo "   ⚠️  GMAIL_PUBSUB_SUBSCRIPTION not set — skipping Pub/Sub update"
fi

echo ""
echo "=========================================="
echo "  Tunnel is running!"
echo "  URL:     $BASE_URL"
echo "  Health:  $BASE_URL/health"
echo "  Events:  $BASE_URL/events"
echo "  PID:     $TUNNEL_PID"
echo "=========================================="
echo ""
echo "Press Ctrl+C to stop the tunnel"

# Cleanup on exit
cleanup() {
  echo ""
  echo "Shutting down tunnel..."
  kill "$TUNNEL_PID" 2>/dev/null
  rm -f "$PID_FILE"
  exit 0
}
trap cleanup INT TERM

# Keep foreground (Ctrl+C works). Without this, the script would exit and the
# backgrounded cloudflared would keep running orphaned.
wait "$TUNNEL_PID"
