# Netlify config for Frontdesk v2
# Login is license-key based (no username/password hashes), so no edge
# injection is needed. Config is fetched at runtime from /api/config.
# No secrets are written to disk during build or sent to the browser.
[build]
  base = "webapp/"
  publish = "public/"
